services:
  backend:
    build: ./see-rest
    container_name: see-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SECURITY_JWT_TOKEN_SECRET_KEY: ${SECURITY_JWT_TOKEN_SECRET_KEY}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
    ports:
      - "8080:8080"
    dns:
        - 8.8.8.8
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./see-client
    container_name: see-frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

  db:
    image: mariadb:11.4
    container_name: see-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: db
    ports:
    - "3308:3306"
    volumes:
      - app_db:/var/lib/mysql
    tmpfs:
      - /tmp:rw,exec,uid=999,gid=999
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: see-nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/see.local:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

networks:
  app_network:

volumes:
  app_db:
